#!/bin/sh

wifi_interface=eth1

case $1 in
   config)
        cat <<'EOM'
graph_title WLAN Networks nearby
graph_vlabel # of WLANs
EOM
        exit 0;;
esac

iwlist_scan=`iwlist $wifi_interface scan`

if [ $? -ne 0 ] ; then
  echo "Scanning for Wifi networks was not successfull. Wrong wifi interface?"
  exit 1
fi

printf "wlans_nearby.value "
echo $iwlist_scan | sed -e 's/Cell /\nCell /' | grep --count 'Cell '
